services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netresearch\UniversalMessenger\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Netresearch\UniversalMessenger\Command\ImportCommand:
        tags:
            - name: 'console.command'
              command: 'universal-messenger:newsletter-channels:import'
              description: 'Imports all active Universal Messenger newsletter channels'
              schedulable: true

    Netresearch\UniversalMessenger\Backend\EventListener\ModifyPageLayoutContentEventListener:
        tags:
            - name: event.listener
              event: TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent

    Netresearch\UniversalMessenger\Backend\EventListener\ModifyBlindedConfigurationOptionsEventListener:
        tags:
            - name: event.listener
              event: TYPO3\CMS\Lowlevel\Event\ModifyBlindedConfigurationOptionsEvent

    Netresearch\UniversalMessenger\Controller\UniversalMessengerController:
        tags: [ 'backend.controller' ]
